"""Demo fixture data for the inventory and order apps.

Pure data: no database access, no import-time side effects. The
``seed_demo_data`` management command is what writes it. Keeping the two
separate means the fixture can be imported by a test without it inserting rows
as a side effect of the import -- which is exactly what the original
``database.py`` did.

Relations are expressed by natural key (a name) rather than by primary key.
The original fixture used ``language_id=37`` and similar, which silently binds
the data to one particular insertion order.
"""

LANGUAGES: tuple[str, ...] = (
    "Abkhaz",
    "Afar",
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Avaric",
    "Avestan",
    "Aymara",
    "Azerbaijani",
    "Bambara",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Chamorro",
    "Chechen",
    "Chinese",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Galician",
    "Georgian",
    "German",
    "Guaraní",
    "Gujarati",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Interlingua",
    "Indonesian",
    "Interlingue",
    "Irish",
    "Igbo",
    "Inupiaq",
    "Ido",
    "Icelandic",
    "Italian",
    "Inuktitut",
    "Japanese",
    "Javanese",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Kinyarwanda",
    "Komi",
    "Kongo",
    "Korean",
    "Kurdish",
    "Latin",
    "Luganda",
    "Lingala",
    "Lao",
    "Lithuanian",
    "Luba-Katanga",
    "Latvian",
    "Manx",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Marshallese",
    "Mongolian",
    "Nauru",
    "North Ndebele",
    "Nepali",
    "Ndonga",
    "Norwegian Nynorsk",
    "Norwegian",
    "Nuosu",
    "South Ndebele",
    "Occitan",
    "Oromo",
    "Oriya",
    "Persian",
    "Polish",
    "Portuguese",
    "Quechua",
    "Romansh",
    "Kirundi",
    "Russian",
    "Sardinian",
    "Sindhi",
    "Northern Sami",
    "Samoan",
    "Sango",
    "Serbian",
    "Shona",
    "Slovak",
    "Slovene",
    "Somali",
    "Southern Sotho",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tamil",
    "Telugu",
    "Tajik",
    "Thai",
    "Tigrinya",
    "Turkmen",
    "Tagalog",
    "Tswana",
    "Turkish",
    "Tsonga",
    "Tatar",
    "Twi",
    "Tahitian",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Walloon",
    "Welsh",
    "Wolof",
    "Western Frisian",
    "Xhosa",
    "Yiddish",
    "Yoruba",
)

INVENTORY_TAGS: tuple[str, ...] = (
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Romance",
    "Sci-Fi",
    "Thriller",
    "Crime",
)

INVENTORY_TYPES: tuple[str, ...] = ("Movie", "Episode", "Version")

ORDER_TAGS: tuple[str, ...] = (
    "San Antonio",
    "Austin",
    "Dallas",
    "Houston",
    "El Paso",
    "Boston",
    "New York",
    "Chicago",
    "Los Angeles",
    "San Francisco",
    "Pending",
    "Delivered",
    "Cancelled",
    "On-hold",
    "Processing",
    "QC",
    "Dubbing",
    "Subbing",
    "Closed Captioning",
    "Transcription",
    "Transcoding",
)

_MATRIX_CAST = ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"]
_LOTR_CAST = ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"]
_SEINFELD_CAST = ["Jerry Seinfeld", "Julia Louis-Dreyfus", "Michael Richards"]


def _seinfeld(episode: int) -> dict:
    return {
        "name": f"Seinfeld Season 1 Episode {episode}",
        "language": "English",
        "type": "Episode",
        "tags": ["Comedy"],
        "metadata": {
            "year": 1990,
            "actors": _SEINFELD_CAST,
            "imdb_rating": 8.8,
            "rotten_tomatoes_rating": 91,
            "film_locations": ["New York, USA"],
        },
    }


INVENTORY_ITEMS: tuple[dict, ...] = (
    {
        "name": "The Matrix",
        "language": "Abkhaz",
        "type": "Version",
        "tags": ["Action"],
        "metadata": {
            "year": 1999,
            "actors": _MATRIX_CAST,
            "imdb_rating": 8.7,
            "rotten_tomatoes_rating": 87,
            "film_locations": ["Sydney, Australia"],
        },
    },
    {
        "name": "The Matrix Reloaded",
        "language": "Assamese",
        "type": "Version",
        "tags": ["Action"],
        "metadata": {
            "year": 2003,
            "actors": _MATRIX_CAST,
            "imdb_rating": 7.2,
            "rotten_tomatoes_rating": 73,
            "film_locations": ["Alameda, California, USA"],
        },
    },
    {
        "name": "The Matrix Revolutions",
        "language": "Assamese",
        "type": "Version",
        "tags": ["Action"],
        "metadata": {
            "year": 2003,
            "actors": _MATRIX_CAST,
            "imdb_rating": 6.7,
            "rotten_tomatoes_rating": 59,
            "film_locations": ["Alameda, California, USA"],
        },
    },
    {
        "name": "Requiem for a Dream",
        "language": "Avestan",
        "type": "Version",
        "tags": ["Drama"],
        "metadata": {
            "year": 2000,
            "actors": ["Ellen Burstyn", "Jared Leto", "Jennifer Connelly"],
            "imdb_rating": 8.3,
            "rotten_tomatoes_rating": 89,
            "film_locations": ["Brooklyn, New York, USA"],
        },
    },
    {
        "name": "The Lord of the Rings: The Fellowship of the Ring",
        "language": "English",
        "type": "Movie",
        "tags": ["Adventure"],
        "metadata": {
            "year": 2001,
            "actors": _LOTR_CAST,
            "imdb_rating": 8.8,
            # The original fixture stored this key as "rotten_toamtoes_rating".
            "rotten_tomatoes_rating": 91,
            "film_locations": ["Wellington, New Zealand"],
        },
    },
    {
        "name": "The Lord of the Rings: The Two Towers",
        "language": "English",
        "type": "Movie",
        "tags": ["Adventure"],
        "metadata": {
            "year": 2002,
            "actors": _LOTR_CAST,
            "imdb_rating": 8.7,
            "rotten_tomatoes_rating": 87,
            "film_locations": ["Wellington, New Zealand"],
        },
    },
    {
        "name": "The Lord of the Rings: The Return of the King",
        "language": "English",
        "type": "Movie",
        "tags": ["Adventure"],
        "metadata": {
            "year": 2003,
            "actors": _LOTR_CAST,
            "imdb_rating": 8.9,
            "rotten_tomatoes_rating": 95,
            "film_locations": ["Wellington, New Zealand"],
        },
    },
    {
        "name": "Titanic",
        "language": "English",
        "type": "Movie",
        "tags": ["Romance"],
        "metadata": {
            "year": 1997,
            "actors": ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane"],
            "imdb_rating": 7.8,
            "rotten_tomatoes_rating": 89,
            "film_locations": ["Rosarito, Baja California, Mexico"],
        },
    },
    {
        "name": "Crash",
        "language": "Guaraní",
        "type": "Version",
        "tags": ["Drama"],
        "metadata": {
            "year": 2004,
            "actors": ["Don Cheadle", "Sandra Bullock", "Matt Dillon"],
            "imdb_rating": 7.8,
            "rotten_tomatoes_rating": 89,
            "film_locations": ["Los Angeles, California, USA"],
        },
    },
    *(_seinfeld(episode) for episode in range(1, 9)),
)

# ``start_offset_days`` and ``embargo_offset_days`` are relative to the day the
# seed runs, so the fixture stays meaningful however long after it was written
# the command is invoked.
ORDERS: tuple[dict, ...] = (
    {
        "inventory": "The Lord of the Rings: The Fellowship of the Ring",
        "start_offset_days": 0,
        "embargo_offset_days": 30,
        "is_active": True,
        "tags": ["San Antonio", "Pending", "Dubbing"],
    },
    {
        # A delivered order whose embargo has already lapsed. The original
        # fixture gave this one a start of "today" and an embargo 30 days in
        # the past, i.e. an embargo that expired before the order began.
        "inventory": "The Lord of the Rings: The Two Towers",
        "start_offset_days": -60,
        "embargo_offset_days": -30,
        "is_active": True,
        "tags": ["Chicago", "Delivered", "Dubbing"],
    },
    {
        "inventory": "The Lord of the Rings: The Return of the King",
        "start_offset_days": 5,
        "embargo_offset_days": 30,
        "is_active": True,
        "tags": ["Boston", "QC", "Subbing", "Transcription"],
    },
    {
        "inventory": "Crash",
        "start_offset_days": 15,
        "embargo_offset_days": 30,
        "is_active": True,
        "tags": ["New York", "Processing", "Dubbing", "Transcoding"],
    },
    {
        "inventory": "The Matrix",
        "start_offset_days": 15,
        "embargo_offset_days": 30,
        "is_active": False,
        "tags": ["Los Angeles", "Cancelled", "Dubbing", "Transcoding"],
    },
)
