# Generated by Django 4.1.7 on 2026-09-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('-created_at', 'id'), 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='inventorylanguage',
            options={'ordering': ('name',), 'verbose_name_plural': 'Inventory Languages'},
        ),
        migrations.AlterModelOptions(
            name='inventorytag',
            options={'ordering': ('name',), 'verbose_name_plural': 'Inventory Tags'},
        ),
        migrations.AlterModelOptions(
            name='inventorytype',
            options={'ordering': ('name',), 'verbose_name_plural': 'Inventory Types'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorylanguage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventorytag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='inventorytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
